package config

import "os"

var (
	PORT        = os.Getenv("PORT")
	IS_INSECURE = os.Getenv("IS_INSECURE")

	USER_MICROSERVICE_CONN         = os.Getenv("USER_MICROSERVICE_CONN")
	CHAT_MICROSSEVICE_CONN         = os.Getenv("CHAT_MICROSERVICE_CONN")
	PROJECT_MICROSSERVICE_CONN     = os.Getenv("PROJECT_MICROSERVICE_CONN")
	NOTIFICATION_MICROSERVICE_CONN = os.Getenv("NOTIFICATION_MICROSERVICE_CONN")
	POST_MICROSERVICE_CONN         = os.Getenv("POST_MICROSERVICE_CONN")

	JWT_SECRET = os.Getenv("JWT_SECRET")
)
